# Generated by Django 4.2.30 on 2026-06-06 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_generatedpost_generatedimage_generationsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
