# Generated by Django 4.2.30 on 2026-06-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_aipostgeneration_unique_constraint'),
        ('chat', '0005_generatedpost_created_at'),
    ]

    operations = [
    ]
