# Generated by Django 4.2.7 on 2024-06-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_merge_20260619_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipostgeneration',
            name='images_status',
            field=models.CharField(
                choices=[
                    ('not_started', 'Not Started'),
                    ('processing', 'Processing'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                ],
                default='not_started',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='aipostgeneration',
            name='images_generation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aipostgeneration',
            name='images_generation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
