# Generated by Django 4.2.30 on 2026-06-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_add_image_generation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aipostgeneration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='aipostgeneration',
            index=models.Index(fields=['user', 'posts_review_complete', '-created_at'], name='chat_aipost_user_id_3588da_idx'),
        ),
        migrations.AddIndex(
            model_name='aipostgeneration',
            index=models.Index(fields=['user', 'images_status'], name='chat_aipost_user_id_146232_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['post', 'created_at'], name='chat_genera_post_id_d81744_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedpost',
            index=models.Index(fields=['session', 'post_index'], name='chat_genera_session_67fc87_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedpost',
            index=models.Index(fields=['created_at'], name='chat_genera_created_674f33_idx'),
        ),
        migrations.AddIndex(
            model_name='generationsession',
            index=models.Index(fields=['user', '-created_at'], name='chat_genera_user_id_a6c85d_idx'),
        ),
        migrations.AddIndex(
            model_name='generationsession',
            index=models.Index(fields=['post_generation', '-created_at'], name='chat_genera_post_ge_f1bee2_idx'),
        ),
    ]
