# Generated by Django 6.0.5 on 2026-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('rotation_interval', models.IntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Success Story Settings',
            },
        ),
    ]
