# Generated by Django 6.0.5 on 2026-05-29 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_successstorysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstorysettings',
            name='featured_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_settings', to='portfolio.successstory'),
        ),
    ]
