# Generated by Django 4.2.30 on 2026-07-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_images',
            field=models.IntegerField(default=10),
        ),
    ]
