# Generated by Django 4.2.30 on 2026-05-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=255)),
                ('business_type_other', models.CharField(blank=True, max_length=255, null=True)),
                ('target_audience', models.CharField(max_length=255)),
                ('marketing_goal', models.CharField(max_length=255)),
                ('image_style', models.CharField(max_length=255)),
                ('mood_style', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
