# Generated by Django 6.0.5 on 2026-05-31 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingresponse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='onboardingresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
