# Generated by Django 4.2.30 on 2026-06-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_update_onboarding_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='onboardingresponse',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='onboarding__user_id_79179a_idx'),
        ),
    ]
