# Generated by Django 4.2.30 on 2026-07-18 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_paymentorder_extra_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
