# Generated by Django 4.2.30 on 2026-06-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['user', '-created_at'], name='support_sup_user_id_c47772_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['chat', 'created_at'], name='support_sup_chat_id_106f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['sender', '-created_at'], name='support_sup_sender__167a0a_idx'),
        ),
    ]
