# Generated by Django 4.2.30 on 2026-06-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='AuditLog',
            index=models.Index(fields=['user', '-created_at'], name='core_userac_user_id_96d8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='AuditLog',
            index=models.Index(fields=['action', '-created_at'], name='core_userac_action_857cb9_idx'),
        ),
    ]
