# Generated by Django 4.2.30 on 2026-07-05 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useractivitylog_core_userac_user_id_96d8ad_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_969660_idx',
            old_name='core_userac_user_id_96d8ad_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_d80c2d_idx',
            old_name='core_userac_action_857cb9_idx',
        ),
    ]
