# Generated by Django 4.2.30 on 2026-07-05 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rename_core_userac_user_id_96d8ad_idx_core_auditl_user_id_969660_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this key', max_length=255)),
                ('key_prefix', models.CharField(db_index=True, editable=False, help_text='First 32 chars of key (for identification)', max_length=32, unique=True)),
                ('key_hash', models.CharField(editable=False, help_text='SHA256 hash of full key', max_length=255)),
                ('scope', models.CharField(choices=[('read', 'Read Only'), ('write', 'Write'), ('admin', 'Admin')], default='read', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Leave blank for never expires', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, help_text='Last IP that used this key', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this key is used for')),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of IPs allowed to use this key (empty = all)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotated_at', models.DateTimeField(blank=True, help_text='When this key was rotated', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('used', 'Used'), ('rotated', 'Rotated'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('ip_blocked', 'IP Blocked'), ('rate_limit', 'Rate Limited')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.apikey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_key_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key Audit Log',
                'verbose_name_plural': 'API Key Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key', '-created_at'], name='core_apikey_api_key_0bc20d_idx'), models.Index(fields=['user', '-created_at'], name='core_apikey_user_id_d6dd68_idx'), models.Index(fields=['event_type', '-created_at'], name='core_apikey_event_t_c74d7b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', '-created_at'], name='core_apikey_user_id_12c3dc_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['status', '-created_at'], name='core_apikey_status_cfcf75_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_prefix'], name='core_apikey_key_pre_e29082_idx'),
        ),
    ]
