# Generated by Django 4.2.30 on 2026-07-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apikey_apikeyauditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyauditlog',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
